name = "Woodvale"
author = "dcxo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c630c6a1ea9773a509dc1fdabf66aa11b4a65000c4ead482a021772b8fefd678"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
