name = "Woodvale"
author = "dcxo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20d9c43eff2f495508bba43b12b485aba528ae315653a06d84608fa499750b1e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
