name = "Woodvale"
author = "dcxo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3754e9367f6627e488bcb3cc7b0bcb5dfbf468da02847ccb9915c386746416f3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
