name: Generate Modrinth Modpack
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-packwiz:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get Packwiz code
        run: |
          git clone https://github.com/packwiz/packwiz.git

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Packwiz
        run: |
          cd packwiz
          go install github.com/packwiz/packwiz@latest

      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Generate Modrinth Modpack
        run: |
          packwiz modrinth export -o Woodvale-${{ github.ref_name }}.mrpack
          packwiz list | sed -e 's/^/- /' >> MODS.md

      - name: release
        uses: actions/create-release@v1
        if: ${{ github.ref_type == 'tag' }}
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body_path: ./MODS.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        if: ${{ github.ref_type == 'tag' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Woodvale-${{ github.ref_name }}.mrpack
          asset_name: Woodvale-${{ github.ref_name }}.mrpack
          asset_content_type: application/x-modrinth-modpack+zip
